FROM node:lts AS build

WORKDIR /app

# Accept build arguments for React environment variables
ARG REACT_APP_REST_URL
ARG REACT_APP_WITH_WALLET_CONNECT
ARG REACT_APP_PROJECT_ID
ARG REACT_APP_CHAIN_ID
ARG REACT_APP_CHAIN_NAME
ARG REACT_APP_CHAIN_NATIVE_CURRENCY_NAME
ARG REACT_APP_CHAIN_NATIVE_CURRENCY_SYMBOL
ARG REACT_APP_CHAIN_RPC_URL
ARG REACT_APP_SCAN_URL
ARG REACT_APP_WEB_3_AUTH_CLIENT_ID

# Set them as environment variables for the build process
ENV REACT_APP_REST_URL=$REACT_APP_REST_URL
ENV REACT_APP_WITH_WALLET_CONNECT=$REACT_APP_WITH_WALLET_CONNECT
ENV REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID
ENV REACT_APP_CHAIN_ID=$REACT_APP_CHAIN_ID
ENV REACT_APP_CHAIN_NAME=$REACT_APP_CHAIN_NAME
ENV REACT_APP_CHAIN_NATIVE_CURRENCY_NAME=$REACT_APP_CHAIN_NATIVE_CURRENCY_NAME
ENV REACT_APP_CHAIN_NATIVE_CURRENCY_SYMBOL=$REACT_APP_CHAIN_NATIVE_CURRENCY_SYMBOL
ENV REACT_APP_CHAIN_RPC_URL=$REACT_APP_CHAIN_RPC_URL
ENV REACT_APP_SCAN_URL=$REACT_APP_SCAN_URL
ENV REACT_APP_WEB_3_AUTH_CLIENT_ID=$REACT_APP_WEB_3_AUTH_CLIENT_ID

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM nginx:alpine AS production

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/build /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
